#!/bin/sh

rm src/RcppExports.o
rm src/IRTpp.so
rm src/util_package.o
rm inst/irtppcpp/libirtppcpp.a
rm inst/irtppcpp/src/estimation/estep.o
rm inst/irtppcpp/src/estimation/mstep.o
rm inst/irtppcpp/src/type/dataset.o
rm inst/irtppcpp/src/type/ghquads.o
rm inst/irtppcpp/src/utils/asa111.o
rm inst/irtppcpp/src/utils/Input.o