# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('IRTppExperimental_rcpp_hello_world', PACKAGE = 'IRTppExperimental')
}

multiTest_dico <- function(RDataset) {
    .Call('IRTppExperimental_multiTest_dico', PACKAGE = 'IRTppExperimental', RDataset)
}

#' uirtestimate
#' @param data -
#' @param model_ -
#' @return list
#' @export
uirtestimate <- function(data, model_, convergenceEpsilon) {
    .Call('IRTppExperimental_uirtestimate', PACKAGE = 'IRTppExperimental', data, model_, convergenceEpsilon)
}

#' abilityinterface
#'  @param zita_par -
#'  @param data -
#'  @param model_ -
#'  @param method -
#'  @param matrix_flag -
#'  @param prob_matrix -
#' @return list
#' @export
abilityinterface <- function(zita_par, data, model_, method, matrix_flag, prob_matrix) {
    .Call('IRTppExperimental_abilityinterface', PACKAGE = 'IRTppExperimental', zita_par, data, model_, method, matrix_flag, prob_matrix)
}

#' mapinterface
#'  @param zita_par -
#'  @param dat -
#'  @param e_model -
#'  @param matrix_flag -
#'  @param prob_matrix -
#' @return list
#' @export
mapinterface <- function(zita_par, dat, e_model, matrix_flag, prob_matrix) {
    .Call('IRTppExperimental_mapinterface', PACKAGE = 'IRTppExperimental', zita_par, dat, e_model, matrix_flag, prob_matrix)
}

#' eapinterface
#'  @param zita_par -
#'  @param dat -
#'  @param e_model -
#'  @param matrix_flag -
#'  @param prob_matrix -
#' @return list
#' @export
eapinterface <- function(zita_par, dat, e_model, matrix_flag, prob_matrix) {
    .Call('IRTppExperimental_eapinterface', PACKAGE = 'IRTppExperimental', zita_par, dat, e_model, matrix_flag, prob_matrix)
}

